### ISSUE TITLE
Really...

### ISSUE THREAD

**Issue by Taki21** [PigRaid/iOS_App#3]
Ok...I do believ you but all i just did was just fork it... And i didnt give myself credit? the owner of grimcraft did ._.

**Comment by Taki21** [comment]
and i was just helping......

**Comment by Taki21** [comment]
Plus i never take credit of someone elses stuff thats that bad...

**Comment by applqpak** [comment]
Ok, well tell the GrimCraft owner to not say he developed it, thank you.

**Comment by Taki21** [comment]
xD sorry if anything confuses you

**Comment by Taki21** [comment]
check [here](https://github.com/SWNetworkDevelopers)
